apiVersion: v1
kind: Service
metadata:
  name: ecommerce-service
  labels:
    app: ecommerce
spec:
  type: LoadBalancer
  ports:
    - port: 80          # External port exposed by the LoadBalancer
      targetPort: 80    # Port on which the container is listening (matches containerPort in Deployment)
      protocol: TCP
  selector:
    app: ecommerce      # Matches the labels in your Deployment's Pod template