apiVersion: apps/v1
kind: Deployment
metadata:
  name: woocommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: woocommerce
  template:
    metadata:
      labels:
        app: woocommerce
    spec:
      containers:
      - name: wordpress
        image: wordpress:php8.3-woocommerce
        ports:
        - containerPort: 80
        env:
        - name: WORDPRESS_DB_HOST
          value: "mysql-service"
        - name: WORDPRESS_DB_USER
          value: "root"