apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecommerce
  template:
    metadata:
      labels:
        app: ecommerce
    spec:
      containers:
      - name: saleor
        image: saleor/saleor:latest
        ports:
        - containerPort: 8000
        env:
        - name: SECRET_KEY
          value: "your-secret-key-here"
        - name: DATABASE_URL
          value: "postgresql://user:pass@postgres:5432/saleor"
        - name: ALLOWED_HOSTS
          value: "*"