apiVersion: v1
kind: Service
metadata:
  name: prestashop-service
spec:
  type: NodePort
  selector:
    app: prestashop  # Matches the label in your deployment
  ports:
    - port: 80        # Service port (cluster-internal)
      targetPort: 80  # Container port (matches containerPort in deployment)
      nodePort: 30001 # External access port (optional, range: 30000-32767)