apiVersion: v1
kind: Pod
metadata:
  name: ecommerce-app
  labels:
    app: ecommerce
spec:
  containers:
    - name: ecommerce-container
      image: awanmbandi/ecommerce-webapp:latest
      ports:
        - containerPort: 80