apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx  # Matches the label in the deployment
  ports:
    - port: 80        # Service port (cluster-internal)
      targetPort: 80   # Container port (matches containerPort in deployment)
      nodePort: 30003 # External access port (optional, range: 30000-32767)