apiVersion: v1
kind: Service
metadata:
  name: ecommerce-service
spec:
  type: NodePort
  selector:
    app: ecommerce
  ports:
    - protocol: TCP
      port: 80              # Service port
      targetPort: 80        # Container port
      nodePort: 30001       # Specify a NodePort (default range: 30000-32767)