apiVersion: apps/v1
kind: Deployment
metadata:
  name: medusa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: medusa
  template:
    metadata:
      labels:
        app: medusa
    spec:
      containers:
      - name: medusa
        image: medusajs/medusa:latest
        ports:
        - containerPort: 9000
        env:
        - name: DATABASE_URL
          value: "postgres://user:pass@postgres:5432/medusa"